import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database…");

  // ── Admin ─────────────────────────────────────────────
  const passwordHash = await bcrypt.hash(
    process.env.ADMIN_SEED_PASSWORD || "Admin@SAM2024!", 12,
  );
  await prisma.admin.upsert({
    where:  { email: "samenterprises2112@gmail.com" },
    update: {},
    create: { email: "samenterprises2112@gmail.com", passwordHash, name: "Super Admin", role: "superadmin" },
  });
  console.log("  ✓ Admin user");

  // ── Site Settings ─────────────────────────────────────
  const settings = [
    { key: "site_name",          value: "SAM Enterprises",              type: "text",  group: "general", label: "Site Name"           },
    { key: "site_tagline",       value: "Premium UPVC Solutions",       type: "text",  group: "general", label: "Tagline"             },
    { key: "established_year",   value: "2008",                         type: "text",  group: "general", label: "Established Year"    },
    { key: "phone_primary",      value: "+91 98765 43210",              type: "text",  group: "contact", label: "Primary Phone"       },
    { key: "phone_office",       value: "+91 44 2345 6789",             type: "text",  group: "contact", label: "Office Phone"        },
    { key: "email_info",         value: "info@samenterprises.com",      type: "text",  group: "contact", label: "Info Email"          },
    { key: "email_sales",        value: "sales@samenterprises.com",     type: "text",  group: "contact", label: "Sales Email"         },
    { key: "whatsapp_number",    value: "919876543210",                 type: "text",  group: "contact", label: "WhatsApp Number"     },
    { key: "address_line1",      value: "42 Industrial Estate, Phase II", type: "text", group: "contact", label: "Address Line 1"    },
    { key: "address_line2",      value: "Ambattur, Chennai, TN 600096", type: "text",  group: "contact", label: "Address Line 2"     },
    { key: "social_instagram",   value: "https://instagram.com/",       type: "url",   group: "social",  label: "Instagram URL"       },
    { key: "social_facebook",    value: "https://facebook.com/",        type: "url",   group: "social",  label: "Facebook URL"        },
    { key: "social_linkedin",    value: "https://linkedin.com/",        type: "url",   group: "social",  label: "LinkedIn URL"        },
    { key: "social_youtube",     value: "",                             type: "url",   group: "social",  label: "YouTube URL"         },
    { key: "admin_email",        value: "info@samenterprises.com",      type: "text",  group: "email",   label: "Admin Notification Email" },
    { key: "email_from_name",    value: "SAM Enterprises",              type: "text",  group: "email",   label: "Email From Name"     },
    { key: "email_from_address", value: "info@samenterprises.com",      type: "text",  group: "email",   label: "Email From Address"  },
    { key: "meta_description",   value: "Custom-fabricated UPVC doors and windows engineered for energy efficiency.", type: "text", group: "seo", label: "Default Meta Description" },
    { key: "meta_keywords",      value: "UPVC windows Chennai, UPVC doors, sliding windows", type: "text", group: "seo", label: "Meta Keywords" },
    { key: "google_analytics",   value: "",                             type: "text",  group: "seo",     label: "Google Analytics ID" },
  ];
  for (const s of settings) {
    await prisma.siteSettings.upsert({ where: { key: s.key }, update: {}, create: s });
  }
  console.log("  ✓ Site settings");

  // ── Page Content ──────────────────────────────────────
  const pageContent = [
    { page: "home", section: "hero",  key: "heading",       value: "Windows\nThat Define\nYour Space."   },
    { page: "home", section: "hero",  key: "subheading",    value: "Custom-fabricated UPVC doors and windows engineered for energy efficiency, acoustic comfort, and lasting elegance." },
    { page: "home", section: "hero",  key: "cta_primary",   value: "Get Free Consultation"               },
    { page: "home", section: "hero",  key: "cta_secondary", value: "Explore Products"                    },
    { page: "home", section: "stats", key: "stat1_value",   value: "2,000+"      },
    { page: "home", section: "stats", key: "stat1_label",   value: "Projects"    },
    { page: "home", section: "stats", key: "stat2_value",   value: "15+"         },
    { page: "home", section: "stats", key: "stat2_label",   value: "Years"       },
    { page: "home", section: "stats", key: "stat3_value",   value: "10yr"        },
    { page: "home", section: "stats", key: "stat3_label",   value: "Warranty"    },
    { page: "home", section: "stats", key: "stat4_value",   value: "98%"         },
    { page: "home", section: "stats", key: "stat4_label",   value: "Satisfaction"},
    { page: "home", section: "cta",   key: "heading",       value: "Get Your Free\nConsultation Today"   },
    { page: "home", section: "cta",   key: "subheading",    value: "Our experts will visit your site and provide a detailed, no-obligation quotation within 48 hours." },
    { page: "home", section: "cta",   key: "button_text",   value: "Book Consultation"                   },
    { page: "home", section: "cta",   key: "phone",         value: "+91 98765 43210"                     },
    { page: "about",   section: "hero", key: "heading",     value: "Crafting Quality\nSince 2008."       },
    { page: "about",   section: "hero", key: "subheading",  value: "From a small fabrication unit in Chennai to South India's most trusted UPVC fenestration company." },
    { page: "contact", section: "hero", key: "heading",     value: "Let's Discuss\nYour Project"         },
    { page: "contact", section: "hero", key: "subheading",  value: "Whether you're planning a new build, renovation, or replacement project, our team is ready to help." },
    { page: "blog",    section: "hero", key: "heading",     value: "Insights & Tips\nfrom Our Experts"   },
    { page: "blog",    section: "hero", key: "subheading",  value: "Tips, guides and project stories from the SAM Enterprises team." },
  ];
  for (const pc of pageContent) {
    await prisma.pageContent.upsert({
      where:  { page_section_key: { page: pc.page, section: pc.section, key: pc.key } },
      update: {},
      create: { ...pc, type: "text" },
    });
  }
  console.log("  ✓ Page content");

  // ── Product Service Categories ─────────────────────────
  const productCats = [
    { slug: "upvc-windows", name: "UPVC Windows",  description: "High-performance UPVC window solutions.", icon: "LayoutGrid", isActive: true, sortOrder: 1 },
    { slug: "upvc-doors",   name: "UPVC Doors",    description: "Precision-engineered UPVC door systems.", icon: "DoorOpen",   isActive: true, sortOrder: 2 },
    { slug: "accessories",  name: "Accessories",   description: "Premium glass, hardware and mesh solutions.", icon: "Wrench", isActive: true, sortOrder: 3 },
  ];
  const catMap: Record<string, string> = {};
  for (const c of productCats) {
    const cat = await prisma.serviceCategory.upsert({ where: { slug: c.slug }, update: {}, create: c });
    catMap[c.slug] = cat.id;
    console.log(`  ✓ ProductCat: ${c.name}`);
  }

  // ── Service Categories (separate) ─────────────────────
  const serviceCats = [
    { slug: "consultation",  name: "Consultation",  description: "Site visit and design services.", isActive: true, sortOrder: 1 },
    { slug: "fabrication",   name: "Fabrication",   description: "Manufacturing and fabrication services.", isActive: true, sortOrder: 2 },
    { slug: "installation",  name: "Installation",  description: "Professional installation services.", isActive: true, sortOrder: 3 },
    { slug: "maintenance",   name: "Maintenance",   description: "After-sales and maintenance services.", isActive: true, sortOrder: 4 },
  ];
  const sCatMap: Record<string, string> = {};
  for (const c of serviceCats) {
    const cat = await prisma.serviceCat.upsert({ where: { slug: c.slug }, update: {}, create: { ...c, icon: "" } });
    sCatMap[c.slug] = cat.id;
    console.log(`  ✓ ServiceCat: ${c.name}`);
  }

  // ── Products ──────────────────────────────────────────
  const products = [
    { slug: "sliding-windows",  name: "Sliding Windows",  category: "Sliding Windows",  subCategory: "UPVC Windows", serviceCategoryId: catMap["upvc-windows"], tagline: "Effortless Movement. Maximum Ventilation.", heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600&q=80", image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80", description: "Our UPVC sliding windows glide effortlessly on precision-engineered stainless steel tracks, delivering maximum ventilation and weather resistance.", metaTitle: "UPVC Sliding Windows Chennai — SAM Enterprises", metaDesc: "Buy custom UPVC sliding windows in Chennai.", features: JSON.stringify(["Precision stainless steel roller tracks","Multi-chambered UPVC profile","EPDM rubber seals","Mosquito mesh option","10-year structural warranty"]), specs: JSON.stringify([{label:"Profile",value:"Grade-A UPVC, 60mm/70mm"},{label:"Track Options",value:"2-track, 3-track, 4-track"},{label:"Glass",value:"5mm toughened / 28mm double-glazed"},{label:"Warranty",value:"10 years structural"}]), whyPoints: JSON.stringify([{number:"01",title:"Smooth Operation",desc:"Stainless steel rollers glide effortlessly even after years of use."},{number:"02",title:"Weather Sealed",desc:"EPDM rubber seals prevent monsoon rain and dust."},{number:"03",title:"Energy Efficient",desc:"Multi-chamber UPVC reduces heat transfer by up to 60%."},{number:"04",title:"Low Maintenance",desc:"UV-stabilised finish never needs painting."}]), variants: JSON.stringify([{name:"Classic 2-Track Slider",image:"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",tags:["2-track","Mosquito mesh","Toughened glass"],description:"The most popular configuration for bedrooms and living rooms."},{name:"Premium 3-Track Slider",image:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80",tags:["3-track","Double-glazed","Soundproof"],description:"Three independent panels for wider openings."},{name:"Villa 4-Track System",image:"https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80",tags:["4-track","Full opening","Villa spec"],description:"Maximum ventilation for large openings."}]), relatedLinks: JSON.stringify([{href:"/products/upvc-windows/casement-windows",label:"Casement Windows"},{href:"/products/upvc-windows/fixed-windows",label:"Fixed Windows"},{href:"/products/accessories/glass-types",label:"Glass Types"}]), tags: JSON.stringify(["windows","sliding","popular"]), isActive: true, sortOrder: 1 },
    { slug: "casement-windows", name: "Casement Windows", category: "Casement Windows", subCategory: "UPVC Windows", serviceCategoryId: catMap["upvc-windows"], tagline: "Open Wide. Seal Tight.", heroImage: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=80", image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80", description: "UPVC casement windows offering excellent ventilation control and a sleek modern look.", metaTitle: "UPVC Casement Windows Chennai — SAM Enterprises", metaDesc: "Custom UPVC casement windows in Chennai.", features: JSON.stringify(["Multi-point locking system","Friction stay hinges","EPDM triple weather seal","Inward or outward opening"]), specs: JSON.stringify([{label:"Profile",value:"60mm / 70mm UPVC"},{label:"Opening Type",value:"Inward / Outward / Top Hung"},{label:"Locking",value:"Multi-point Roto or Siegenia"},{label:"Warranty",value:"10 years structural"}]), whyPoints: JSON.stringify([{number:"01",title:"Maximum Ventilation",desc:"Opens fully for unobstructed airflow."},{number:"02",title:"Superior Seal",desc:"Airtight and watertight when closed."},{number:"03",title:"Secure Locking",desc:"Multi-point locks engage simultaneously."},{number:"04",title:"Noise Reduction",desc:"Up to Rw 38 dB noise reduction."}]), variants: JSON.stringify([{name:"Side-Hung Casement",image:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80",tags:["Side hung","Outward opening"],description:"Classic side-hung casement."},{name:"Top-Hung Casement",image:"https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80",tags:["Top hung","Rain-protected"],description:"Opens from the top — allows ventilation during rain."}]), relatedLinks: JSON.stringify([{href:"/products/upvc-windows/sliding-windows",label:"Sliding Windows"},{href:"/products/accessories/hardware",label:"Hardware"}]), tags: JSON.stringify(["windows","casement"]), isActive: true, sortOrder: 2 },
    { slug: "fixed-windows",    name: "Fixed Windows",    category: "Fixed Windows",    subCategory: "UPVC Windows", serviceCategoryId: catMap["upvc-windows"], tagline: "Pure Light. Zero Compromise.", heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1600&q=80", image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80", description: "Non-opening fixed windows that maximise natural light while maintaining thermal performance.", metaTitle: "UPVC Fixed Windows Chennai — SAM Enterprises", metaDesc: "Custom fixed UPVC windows in Chennai.", features: JSON.stringify(["No moving parts — zero maintenance","Maximum glass area","Custom shapes available","Double or triple glazing"]), specs: JSON.stringify([{label:"Profile",value:"60mm UPVC fixed frame"},{label:"Glass",value:"5mm toughened / 28mm double-glazed"},{label:"Max Size",value:"Up to 3000mm × 2400mm"},{label:"Warranty",value:"10 years structural"}]), whyPoints: JSON.stringify([{number:"01",title:"Maximise Light",desc:"More glass, more natural light."},{number:"02",title:"Best Insulation",desc:"Permanent airtight seal."},{number:"03",title:"Custom Shapes",desc:"Arched, triangular, circular."},{number:"04",title:"Mix and Match",desc:"Combine with opening casements."}]), variants: JSON.stringify([{name:"Standard Fixed",image:"https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80",tags:["Rectangular","Double-glazed"],description:"Classic rectangular fixed window."},{name:"Panoramic Fixed",image:"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",tags:["Floor to ceiling","Feature wall"],description:"Full-height glazing for a dramatic feature wall."}]), relatedLinks: JSON.stringify([{href:"/products/upvc-windows/sliding-windows",label:"Sliding Windows"},{href:"/products/accessories/glass-types",label:"Glass Types"}]), tags: JSON.stringify(["windows","fixed"]), isActive: true, sortOrder: 3 },
    { slug: "sliding-doors",    name: "Sliding Doors",    category: "Sliding Doors",    subCategory: "UPVC Doors", serviceCategoryId: catMap["upvc-doors"], tagline: "Glide Open. Save Space.", heroImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600&q=80", image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80", description: "Space-saving UPVC sliding doors for balconies, patios and room dividers.", metaTitle: "UPVC Sliding Doors Chennai — SAM Enterprises", metaDesc: "Custom UPVC sliding doors in Chennai.", features: JSON.stringify(["Anti-lift roller system","Stainless steel guide track","Multi-point hook bolt locking","Double-glazed panels"]), specs: JSON.stringify([{label:"Profile",value:"70mm UPVC sliding system"},{label:"Track",value:"2-track, 3-track, 4-track"},{label:"Glass",value:"6mm toughened / 28mm double-glazed"},{label:"Warranty",value:"10 years structural"}]), whyPoints: JSON.stringify([{number:"01",title:"Space Saving",desc:"Panels slide — no floor area lost."},{number:"02",title:"Anti-Lift Security",desc:"Impossible to remove panels from outside."},{number:"03",title:"Dust Proof",desc:"Brush seals prevent dust and insects."},{number:"04",title:"Accessible",desc:"Low-profile threshold option."}]), variants: JSON.stringify([{name:"2-Panel Slider",image:"https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",tags:["2-panel","Balcony"],description:"Classic balcony door solution."},{name:"4-Panel Slider",image:"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",tags:["4-panel","Full width"],description:"Maximum width opening for patios."}]), relatedLinks: JSON.stringify([{href:"/products/upvc-doors/french-doors",label:"French Doors"},{href:"/products/accessories/glass-types",label:"Glass Types"}]), tags: JSON.stringify(["doors","sliding"]), isActive: true, sortOrder: 4 },
    { slug: "french-doors",     name: "French Doors",     category: "French Doors",     subCategory: "UPVC Doors", serviceCategoryId: catMap["upvc-doors"], tagline: "Classic Elegance. Modern Performance.", heroImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1600&q=80", image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80", description: "Elegant UPVC French doors connecting indoor and outdoor living spaces.", metaTitle: "UPVC French Doors Chennai — SAM Enterprises", metaDesc: "Custom UPVC French doors in Chennai.", features: JSON.stringify(["Double-leaf design","Multi-point locking on both leaves","EPDM seal on all four sides","Low threshold option"]), specs: JSON.stringify([{label:"Profile",value:"70mm outward-opening UPVC"},{label:"Glass",value:"6mm toughened / 28mm double-glazed"},{label:"Max Width",value:"Up to 2400mm pair"},{label:"Warranty",value:"10 years structural"}]), whyPoints: JSON.stringify([{number:"01",title:"Full Opening",desc:"Both leaves open fully."},{number:"02",title:"Elegant Design",desc:"Traditional astragal bar detail."},{number:"03",title:"Weatherproof",desc:"EPDM seals on all four sides."},{number:"04",title:"Secure",desc:"Multi-point locks on both leaves."}]), variants: JSON.stringify([{name:"Classic French Door",image:"https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80",tags:["Double leaf","Astragal bar"],description:"Classic double leaf French door."}]), relatedLinks: JSON.stringify([{href:"/products/upvc-doors/sliding-doors",label:"Sliding Doors"},{href:"/products/upvc-doors/folding-doors",label:"Folding Doors"}]), tags: JSON.stringify(["doors","french"]), isActive: true, sortOrder: 5 },
    { slug: "folding-doors",    name: "Folding Doors",    category: "Folding Doors",    subCategory: "UPVC Doors", serviceCategoryId: catMap["upvc-doors"], tagline: "The Full Opening Experience.", heroImage: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1600&q=80", image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=600&q=80", description: "Bi-fold UPVC doors that fold flat for a wide-open connection to outdoor spaces.", metaTitle: "UPVC Bi-Fold Doors Chennai — SAM Enterprises", metaDesc: "UPVC bi-fold doors in Chennai.", features: JSON.stringify(["90% clear opening width","Top-hung track system","2 to 6 panel configurations","Double-glazed panels standard"]), specs: JSON.stringify([{label:"Profile",value:"Grade-A UPVC, 70mm bi-fold"},{label:"Panel Config",value:"2-fold to 6-fold"},{label:"Max Height",value:"Up to 2400mm"},{label:"Warranty",value:"10 years structural"}]), whyPoints: JSON.stringify([{number:"01",title:"90% Clear Opening",desc:"More clear opening width than any other door."},{number:"02",title:"Trip-Free",desc:"No raised floor rail."},{number:"03",title:"Thermally Efficient",desc:"Double-glazed panels standard."},{number:"04",title:"Architecturally Stunning",desc:"Minimal frame lines, maximum glass."}]), variants: JSON.stringify([{name:"4-Panel Bi-Fold",image:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=600&q=80",tags:["4-panel","Double-glazed"],description:"Ideal for dining room garden access."},{name:"6-Panel Bi-Fold",image:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",tags:["6-panel","Full wall"],description:"Maximum opening for large living areas."}]), relatedLinks: JSON.stringify([{href:"/products/upvc-doors/sliding-doors",label:"Sliding Doors"},{href:"/products/accessories/hardware",label:"Hardware"}]), tags: JSON.stringify(["doors","folding"]), isActive: true, sortOrder: 6 },
    { slug: "glass-types",      name: "Glass Types",      category: "Accessories", subCategory: "Glass", serviceCategoryId: catMap["accessories"], tagline: "The Right Glass Changes Everything.", heroImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600&q=80", image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80", description: "Full range of certified glazing options for thermal, acoustic and safety performance.", metaTitle: "UPVC Window Glass Types — SAM Enterprises", metaDesc: "Toughened, double-glazed, acoustic glass in Chennai.", features: JSON.stringify(["Toughened safety glass — BS EN 12150","Double-glazed units with argon gas","Acoustic laminated glass — up to Rw 42 dB","Solar control glass"]), specs: JSON.stringify([{label:"Toughened Single",value:"4mm, 5mm, 6mm, 8mm"},{label:"Double Glazed",value:"4-16-4mm, 5-16-5mm"},{label:"Acoustic",value:"Rw 34–42 dB"},{label:"Gas Fill",value:"Argon standard"}]), whyPoints: JSON.stringify([{number:"01",title:"Thermal Control",desc:"Reduce heat transfer dramatically."},{number:"02",title:"Noise Reduction",desc:"Up to 42 dB noise reduction."},{number:"03",title:"Safety Certified",desc:"EN-certified toughened glass."},{number:"04",title:"Solar Management",desc:"Blocks up to 70% solar heat."}]), variants: JSON.stringify([{name:"Toughened Clear",image:"https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",tags:["Safety","Standard"],description:"EN-certified toughened safety glass."},{name:"Double-Glazed Unit",image:"https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80",tags:["Thermal","Acoustic"],description:"Recommended upgrade for all homes."}]), relatedLinks: JSON.stringify([{href:"/products/accessories/hardware",label:"Hardware"},{href:"/products/upvc-windows/sliding-windows",label:"Sliding Windows"}]), tags: JSON.stringify(["accessories","glass"]), isActive: true, sortOrder: 7 },
    { slug: "hardware",         name: "Hardware",         category: "Accessories", subCategory: "Hardware", serviceCategoryId: catMap["accessories"], tagline: "European Quality. Indian Durability.", heroImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1600&q=80", image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80", description: "Certified European hardware from Roto, Siegenia and Maco.", metaTitle: "UPVC Window Hardware — SAM Enterprises", metaDesc: "Roto, Siegenia, Maco hardware in Chennai.", features: JSON.stringify(["Roto NT friction stays","Siegenia roller systems","Maco multi-point lock bars","SS316 stainless steel handles"]), specs: JSON.stringify([{label:"Casement",value:"Roto NT system"},{label:"Sliding",value:"Siegenia — 50kg rated"},{label:"Doors",value:"Maco multi-point — 3 to 5 points"},{label:"Warranty",value:"5 years all hardware"}]), whyPoints: JSON.stringify([{number:"01",title:"European Brands",desc:"Roto, Siegenia and Maco — world leaders."},{number:"02",title:"Coastal Rated",desc:"SS316 resistant to salt air."},{number:"03",title:"Security Certified",desc:"RC2 burglar resistance."},{number:"04",title:"Smooth for Life",desc:"Smooth operation for 15+ years."}]), variants: JSON.stringify([{name:"Roto NT Casement Set",image:"https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80",tags:["Casement","German"],description:"Complete friction stay and lock set."}]), relatedLinks: JSON.stringify([{href:"/products/accessories/glass-types",label:"Glass Types"},{href:"/products/upvc-windows/casement-windows",label:"Casement Windows"}]), tags: JSON.stringify(["accessories","hardware"]), isActive: true, sortOrder: 8 },
    { slug: "mesh-screens",     name: "Mesh / Screens",   category: "Accessories", subCategory: "Screens", serviceCategoryId: catMap["accessories"], tagline: "Breathe Free. Keep Insects Out.", heroImage: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&q=80", image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=600&q=80", description: "Integrated and retractable mosquito screens for UPVC windows and doors.", metaTitle: "Mosquito Mesh Screens — SAM Enterprises", metaDesc: "Integrated mosquito screens for UPVC windows in Chennai.", features: JSON.stringify(["18×16 fibreglass mesh","Pet-resistant heavy-duty option","Fixed, retractable and pleated options","UV-stable mesh"]), specs: JSON.stringify([{label:"Standard Mesh",value:"18×16 fibreglass"},{label:"Frame",value:"Aluminium powder-coated"},{label:"UV Rating",value:"UV-stable — 15+ year life"},{label:"Warranty",value:"5 years frame, 2 years mesh"}]), whyPoints: JSON.stringify([{number:"01",title:"Insect-Free",desc:"Stops mosquitoes and fine dust."},{number:"02",title:"Invisible Design",desc:"Retractable screens roll away."},{number:"03",title:"UV Stable",desc:"No cracking or yellowing."},{number:"04",title:"Easy to Clean",desc:"Pop out for simple washing."}]), variants: JSON.stringify([{name:"Fixed Mesh Frame",image:"https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=600&q=80",tags:["Fixed","Budget"],description:"Most affordable and durable option."},{name:"Retractable Roller",image:"https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",tags:["Retractable","Invisible"],description:"Rolls away into a slim cassette."}]), relatedLinks: JSON.stringify([{href:"/products/accessories/glass-types",label:"Glass Types"},{href:"/products/upvc-windows/sliding-windows",label:"Sliding Windows"}]), tags: JSON.stringify(["accessories","screens"]), isActive: true, sortOrder: 9 },
  ];

  for (const p of products) {
    await prisma.product.upsert({
      where:  { slug: p.slug },
      update: { serviceCategoryId: p.serviceCategoryId, tagline: p.tagline, heroImage: p.heroImage },
      create: p,
    });
    console.log(`  ✓ Product: ${p.name}`);
  }

  // ── Service Items (replaces old Service model) ─────────
  const serviceItems = [
    { slug: "free-site-consultation", name: "Free Site Consultation", category: "Consultation", serviceCatId: sCatMap["consultation"], tagline: "No Cost. No Obligation.", image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=600&q=80", heroImage: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=1600&q=80", description: "Our experts visit your site at no cost, assess requirements, take precise measurements and recommend the best UPVC solutions for your space.", features: JSON.stringify(["Free site visit — no charges ever","Precise measurements taken on-site","Material and colour recommendations","Written summary of recommendations"]), specs: JSON.stringify([{label:"Duration",value:"1–2 hours on site"},{label:"Coverage",value:"Chennai and surrounding areas"},{label:"Cost",value:"Completely free"},{label:"Response Time",value:"Within 24–48 hours"}]), whyPoints: JSON.stringify([{number:"01",title:"Zero Cost",desc:"No charges for site visit or consultation."},{number:"02",title:"Expert Advice",desc:"15+ years experienced consultants."},{number:"03",title:"No Obligation",desc:"No pressure to place an order."},{number:"04",title:"Detailed Report",desc:"Written summary provided after visit."}]), variants: JSON.stringify([]), relatedLinks: JSON.stringify([{href:"/services/fabrication/precision-fabrication",label:"Precision Fabrication"},{href:"/services/installation/professional-installation",label:"Installation"}]), metaTitle: "Free Site Consultation — SAM Enterprises", metaDesc: "Book a free site visit with SAM Enterprises.", isActive: true, sortOrder: 1 },
    { slug: "custom-design-quotation", name: "Custom Design & Quotation", category: "Consultation", serviceCatId: sCatMap["consultation"], tagline: "Tailored to Your Vision.", image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=80", heroImage: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1600&q=80", description: "Tailored design proposal with material samples, colour options and a fully transparent itemised quotation — no hidden charges.", features: JSON.stringify(["Custom design proposal","Material samples provided","Itemised transparent quotation","Colour and finish options"]), specs: JSON.stringify([{label:"Turnaround",value:"Within 48 hours of site visit"},{label:"Formats",value:"PDF or printed quotation"},{label:"Validity",value:"Quote valid for 30 days"},{label:"Cost",value:"Free"}]), whyPoints: JSON.stringify([{number:"01",title:"Transparent Pricing",desc:"Every item clearly listed — no surprises."},{number:"02",title:"Material Samples",desc:"See and touch before you decide."},{number:"03",title:"Fast Turnaround",desc:"Quote in 48 hours."},{number:"04",title:"Multiple Options",desc:"Compare different configurations."}]), variants: JSON.stringify([]), relatedLinks: JSON.stringify([{href:"/services/consultation/free-site-consultation",label:"Free Site Consultation"},{href:"/services/fabrication/precision-fabrication",label:"Fabrication"}]), metaTitle: "Custom Design & Quotation — SAM Enterprises", metaDesc: "Get a custom design and transparent quote.", isActive: true, sortOrder: 2 },
    { slug: "precision-fabrication", name: "Precision Fabrication", category: "Fabrication", serviceCatId: sCatMap["fabrication"], tagline: "Engineered to Exact Measurements.", image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80", heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1600&q=80", description: "Every unit manufactured at our in-house facility using Grade-A UPVC profiles and certified European hardware to exact measurements.", features: JSON.stringify(["In-house fabrication facility","Grade-A UPVC profiles only","European hardware — Roto, Siegenia, Maco","Quality checked before dispatch"]), specs: JSON.stringify([{label:"Profile Grade",value:"Grade-A UPVC"},{label:"Hardware",value:"European certified brands"},{label:"Lead Time",value:"7–14 working days"},{label:"Quality Check",value:"100% inspection before dispatch"}]), whyPoints: JSON.stringify([{number:"01",title:"In-House Control",desc:"Full quality control from start to finish."},{number:"02",title:"Exact Measurements",desc:"Manufactured to ±1mm accuracy."},{number:"03",title:"Premium Materials",desc:"Grade-A UPVC and European hardware."},{number:"04",title:"Pre-Dispatch Check",desc:"100% quality inspection."}]), variants: JSON.stringify([]), relatedLinks: JSON.stringify([{href:"/services/installation/professional-installation",label:"Installation"},{href:"/products/accessories/hardware",label:"Hardware"}]), metaTitle: "Precision UPVC Fabrication — SAM Enterprises", metaDesc: "Grade-A UPVC fabrication in Chennai.", isActive: true, sortOrder: 3 },
    { slug: "professional-installation", name: "Professional Installation", category: "Installation", serviceCatId: sCatMap["installation"], tagline: "Perfect Fit. Every Time.", image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80", heroImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1600&q=80", description: "Certified installation teams ensure perfect fit, alignment and weatherproofing with minimal disruption to your routine.", features: JSON.stringify(["Certified installation teams","Minimal disruption to daily routine","Perfect alignment guaranteed","Site cleaned after installation"]), specs: JSON.stringify([{label:"Team Size",value:"2–4 certified installers"},{label:"Duration",value:"1 day for up to 10 units"},{label:"Guarantee",value:"Installation defects covered 1 year"},{label:"Cleanup",value:"Full site cleanup included"}]), whyPoints: JSON.stringify([{number:"01",title:"Certified Teams",desc:"All installers trained and certified."},{number:"02",title:"Minimal Disruption",desc:"Work completed in one day."},{number:"03",title:"Perfect Alignment",desc:"Laser-level alignment every time."},{number:"04",title:"Clean Site",desc:"We clean up completely after work."}]), variants: JSON.stringify([]), relatedLinks: JSON.stringify([{href:"/services/maintenance/maintenance-repair",label:"Maintenance & Repair"},{href:"/services/fabrication/precision-fabrication",label:"Fabrication"}]), metaTitle: "Professional UPVC Installation — SAM Enterprises", metaDesc: "Certified UPVC installation in Chennai.", isActive: true, sortOrder: 4 },
    { slug: "maintenance-repair", name: "Maintenance & Repair", category: "Maintenance", serviceCatId: sCatMap["maintenance"], tagline: "Keep It Running Perfectly.", image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80", heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600&q=80", description: "Annual maintenance contracts, hardware servicing and rapid-response repair visits keep your windows performing for decades.", features: JSON.stringify(["Annual maintenance contracts","Hardware servicing and lubrication","Rapid-response repair visits","Genuine spare parts used"]), specs: JSON.stringify([{label:"AMC Duration",value:"12 months"},{label:"Visits",value:"2 scheduled visits per year"},{label:"Response Time",value:"Within 48 hours for repairs"},{label:"Parts",value:"Genuine European hardware only"}]), whyPoints: JSON.stringify([{number:"01",title:"Proactive Care",desc:"Prevent issues before they occur."},{number:"02",title:"Fast Response",desc:"Repair visits within 48 hours."},{number:"03",title:"Genuine Parts",desc:"Only original European hardware used."},{number:"04",title:"Long Life",desc:"Properly maintained windows last 30+ years."}]), variants: JSON.stringify([]), relatedLinks: JSON.stringify([{href:"/services/maintenance/after-sales-support",label:"After-Sales Support"},{href:"/services/installation/professional-installation",label:"Installation"}]), metaTitle: "UPVC Window Maintenance & Repair — SAM Enterprises", metaDesc: "UPVC maintenance and repair services in Chennai.", isActive: true, sortOrder: 5 },
    { slug: "after-sales-support", name: "After-Sales Support", category: "Maintenance", serviceCatId: sCatMap["maintenance"], tagline: "We're Here Long After Installation.", image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80", heroImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600&q=80", description: "Dedicated after-sales care with a direct support line, documented warranty claims and priority scheduling for all customers.", features: JSON.stringify(["Dedicated support line","Warranty claim management","Priority scheduling for existing customers","Digital service records"]), specs: JSON.stringify([{label:"Support Hours",value:"Mon–Sat, 9 AM – 6 PM"},{label:"Warranty",value:"10 years structural, 5 years hardware"},{label:"Priority",value:"Existing customers get priority"},{label:"Records",value:"Digital service history maintained"}]), whyPoints: JSON.stringify([{number:"01",title:"Direct Support",desc:"Reach our team directly — no call centres."},{number:"02",title:"Documented Claims",desc:"All warranty claims properly documented."},{number:"03",title:"Priority Service",desc:"Existing customers always come first."},{number:"04",title:"Digital Records",desc:"Your service history always accessible."}]), variants: JSON.stringify([]), relatedLinks: JSON.stringify([{href:"/services/maintenance/maintenance-repair",label:"Maintenance & Repair"},{href:"/services/consultation/free-site-consultation",label:"Book Consultation"}]), metaTitle: "After-Sales Support — SAM Enterprises", metaDesc: "Dedicated after-sales support from SAM Enterprises.", isActive: true, sortOrder: 6 },
  ];

  for (const s of serviceItems) {
    const { serviceCatId, ...rest } = s;
    await prisma.serviceItem.upsert({
      where:  { slug: s.slug },
      update: { serviceCatId },
      create: { ...rest, serviceCatId, subCategory: "", tags: JSON.stringify([]) },
    });
    console.log(`  ✓ ServiceItem: ${s.name}`);
  }

  // ── Team ──────────────────────────────────────────────
  const team = [
    { name: "Rajesh Kumar", role: "Founder & CEO",      bio: "With 20+ years in the UPVC industry, Rajesh founded SAM Enterprises to bring European fenestration quality to Indian homes.", isLeader: true,  sortOrder: 1 },
    { name: "Priya Sharma", role: "Head of Operations", bio: "Priya oversees all project delivery and quality assurance.",  isLeader: false, sortOrder: 2 },
    { name: "Arun Venkat",  role: "Lead Fabricator",    bio: "Arun leads our fabrication team with 15 years of experience.", isLeader: false, sortOrder: 3 },
  ];
  for (const m of team) {
    const ex = await prisma.teamMember.findFirst({ where: { name: m.name } });
    if (!ex) await prisma.teamMember.create({ data: { ...m, image: "", isActive: true } });
    console.log(`  ✓ Team: ${m.name}`);
  }

  // ── Testimonials ──────────────────────────────────────
  const testimonials = [
    { name: "Anand Krishnamurthy", location: "Chennai",    project: "Home Renovation — 24 Sliding Windows",   quote: "The quality of SAM's UPVC windows is outstanding. Zero rattling, perfect sealing, and the team was professional throughout.", rating: 5, sortOrder: 1 },
    { name: "Meera Subramanian",   location: "Coimbatore", project: "New Villa — Doors & Windows Package",     quote: "We replaced all our aluminium windows with SAM's UPVC range. The difference in noise reduction is remarkable.",               rating: 5, sortOrder: 2 },
    { name: "Vikram Naidu",        location: "Hyderabad",  project: "Commercial Office — 48 Units",            quote: "Highly recommend SAM Enterprises. On-time delivery, zero defects, and excellent after-sales support.",                       rating: 5, sortOrder: 3 },
    { name: "Lakshmi Iyer",        location: "Bangalore",  project: "Apartment Renovation",                    quote: "The sliding windows are buttery smooth and the mosquito mesh is a great touch.",                                          rating: 5, sortOrder: 4 },
  ];
  for (const t of testimonials) {
    const ex = await prisma.testimonial.findFirst({ where: { name: t.name } });
    if (!ex) await prisma.testimonial.create({ data: { ...t, avatar: "", isActive: true } });
    console.log(`  ✓ Testimonial: ${t.name}`);
  }

  console.log("\n✅ Seed complete!");
  console.log("🔑 Admin: samenterprises2112@gmail.com / Admin@SAM2024!");
}

main().catch(console.error).finally(() => prisma.$disconnect());
